const $=s=>document.querySelector(s),defectOrder=Object.keys(ImageQuality.defects);
const featuredChecks=['1640 × 840 px master; include the dimensions in the filename','Keep the main entity centered and visible in every crop','Use consistent brand typography, colors, component count, and layout','Keep image text to two lines; do not block the main entity','Keep the logo readable, watermarked, and in the same position','Match image text with alt text and the image title attribute','Use picture/source variants for mobile and the full-width asset for OG/Twitter','Add IPTC title, author, description, keywords, copyright, and contact details'];
const inlineChecks=['Use the image only for its subsection and place it at the section end','Keep the same logo corner, typography, and brand colors as featured images','Use text derived from the heading and facts from the paragraph','Keep the image at 840 px maximum width; adjust height to the design','Export as AVIF and use the heading concept in the filename','Wrap in figure and expand the image meaning with figcaption','Introduce the graphic in surrounding copy and explain what it shows','Use sourced, factual components, labels, icons, diagrams, or formulas where relevant'];
function prettyType(type){return ImageQuality.defects[type].name}
defectOrder.forEach(type=>{const meta=ImageQuality.defects[type];$('#defectInputs').insertAdjacentHTML('beforeend',`<label class="defect-row"><span><b>${meta.name}</b><small>${type}</small></span><input type="range" min="0" max="1" step="0.01" value="0" data-defect="${type}"><output>0.00</output></label>`)});
function scores(){return Object.fromEntries([...document.querySelectorAll('[data-defect]')].map(el=>[el.dataset.defect,+el.value]))}
function mode(){return document.querySelector('input[name="mode"]:checked').value}
function sop(){const checks=mode()==='featured'?featuredChecks:inlineChecks;$('#sopTitle').textContent=mode()==='featured'?'Featured image checklist':'Inline image checklist';$('#sopChecklist').innerHTML=checks.map(x=>`<label><input type="checkbox"><span>${x}</span></label>`).join('')}
function update(){
  document.querySelectorAll('.defect-row').forEach(row=>{const input=row.querySelector('input'),output=row.querySelector('output');output.value=(+input.value).toFixed(2);row.dataset.severity=ImageQuality.severity(input.value)});
  const result=ImageQuality.assess(scores(),mode());$('#score').textContent=result.score;$('#status').textContent=result.status;$('#status').dataset.status=result.status;$('#resultTitle').textContent=result.title;
  $('#summary').textContent=result.active.length?`${result.active.length} defect${result.active.length===1?'':'s'} reached the review threshold. Address the highest-confidence issues first.`:'No defect confidence reaches the 0.25 review threshold.';
  $('#priorityList').innerHTML=result.active.slice(0,4).map(x=>`<div class="priority" data-severity="${x.severity}"><span>${x.severity}</span><b>${x.name}</b><strong>${x.confidence.toFixed(2)}</strong></div>`).join('')||'<p class="empty">No active defects.</p>';
  $('#actionPlan').innerHTML=result.active.length?result.active.map((x,i)=>`<article><div class="action-no">${String(i+1).padStart(2,'0')}</div><div><p class="action-label">${x.severity} · confidence ${x.confidence.toFixed(2)}</p><h3>${x.name}</h3><p>${x.fix}</p><div class="verify"><b>Verify</b>${x.check}</div></div></article>`).join(''):`<div class="clean"><strong>Ready for the SOP check.</strong><p>No quality defect is above 0.25. Complete the delivery checklist before publishing.</p></div>`;
  window.currentAssessment=result;sop();
}
$('#advisor').addEventListener('input',update);$('#advisor').addEventListener('change',update);
$('#applyJson').addEventListener('click',()=>{try{const found=ImageQuality.extract(JSON.parse($('#jsonInput').value));if(!Object.keys(found).length)throw new Error('No supported defects found.');document.querySelectorAll('[data-defect]').forEach(el=>el.value=found[el.dataset.defect]??0);$('#jsonState').textContent=`Applied ${Object.keys(found).length} defect score${Object.keys(found).length===1?'':'s'}.`;update()}catch(error){$('#jsonState').textContent=error.message}});
$('#reset').addEventListener('click',()=>{document.querySelectorAll('[data-defect]').forEach(el=>el.value=0);$('#jsonInput').value='';$('#jsonState').textContent='';update()});
$('#copy').addEventListener('click',async()=>{const r=window.currentAssessment;const text=`${r.title}\nQuality score: ${r.score}/100\n${r.active.map((x,i)=>`${i+1}. ${x.name} (${x.confidence.toFixed(2)}): ${x.fix}`).join('\n')||'No active defects above 0.25.'}`;await navigator.clipboard.writeText(text);$('#copyState').textContent='Recommendations copied.'});update();
