window.QUERY_CATALOG = [
  {
    "id": "q01",
    "title": "Pages Google stopped serving",
    "category": "Lifecycle",
    "summary": "Find URLs that earned impressions at the beginning of the export but none at the end.",
    "sql": "WITH bounds AS (\n  SELECT MIN(data_date) AS d0, MAX(data_date) AS d1\n  FROM `{{TABLE}}`\n)\nSELECT\n  url,\n  SUM(IF(data_date <= DATE_ADD((SELECT d0 FROM bounds), INTERVAL 30 DAY), impressions, 0)) AS impressions_first_month,\n  SUM(IF(data_date >= DATE_SUB((SELECT d1 FROM bounds), INTERVAL 30 DAY), impressions, 0)) AS impressions_last_month,\n  MAX(IF(impressions > 0, data_date, NULL)) AS last_impression_date,\n  SUM(impressions) AS impressions_total,\n  SUM(clicks) AS clicks_total\nFROM `{{TABLE}}`\nGROUP BY url\nHAVING impressions_first_month >= 1 AND impressions_last_month = 0\nORDER BY impressions_first_month DESC",
    "notes": "- WITH bounds AS ( : makes a small helper table called bounds.\n- SELECT MIN(data_date), MAX(data_date) : finds the first day and the last day in your data. d0 is the first day, d1 is the last day.\n- FROM ...searchdata_url_impression : the Search Console export table.\n- ) : the helper table ends here.\n- SELECT : start of the real report.\n- url : one line in the report for each page.\n- impressions_first_month : counts impressions only in the first 30 days of the data.\n- impressions_last_month : counts impressions only in the last 30 days of the data.\n- last_impression_date : the last day the page was shown in search at all.\n- impressions_total : all impressions the page ever got.\n- clicks_total : all clicks the page ever got.\n- FROM ...searchdata_url_impression : reads the same table again for the report.\n- GROUP BY url : puts all the daily rows of one page together into one line.\n- HAVING first_month >= 1 AND last_month = 0 : keeps only pages that had impressions at the start and zero impressions at the end.\n- ORDER BY impressions_first_month DESC : biggest losses first.\n\n- In short: it shows you the pages Google used to show and stopped showing.\n\n- Note: each window is really 31 days, because both end dates are included.\n- Note: if your data covers less than about 61 days, the two windows overlap and the report comes back almost empty.\n- Note: the export has no rows for days with zero impressions, so the zero at the end comes from missing rows, not from a real recorded zero.\n- Note: the table is read twice, so on big sites add a data_date filter to lower the cost.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q02",
    "title": "URL lifecycle table",
    "category": "Lifecycle",
    "summary": "Label every served URL as new, active, or dropped.",
    "sql": "-- 1. LIFECYCLE TABLE: first seen, last seen, and status for every URL\nDECLARE gap_days INT64 DEFAULT 28;\n\nWITH per_url AS (\n  SELECT\n    url,\n    MIN(data_date) AS first_seen,\n    MAX(data_date) AS last_seen,\n    COUNT(DISTINCT data_date) AS active_days,\n    SUM(impressions) AS impressions_total,\n    SUM(clicks) AS clicks_total\n  FROM `{{TABLE}}`\n  WHERE impressions > 0\n  GROUP BY url\n),\nbounds AS (\n  SELECT MAX(data_date) AS d1 FROM `{{TABLE}}`\n)\nSELECT\n  url,\n  first_seen,\n  last_seen,\n  active_days,\n  DATE_DIFF(last_seen, first_seen, DAY) + 1 AS lifespan_days,\n  DATE_DIFF((SELECT d1 FROM bounds), last_seen, DAY) AS days_since_last_seen,\n  impressions_total,\n  clicks_total,\n  CASE\n    WHEN DATE_DIFF((SELECT d1 FROM bounds), last_seen, DAY) >= gap_days THEN 'dropped'\n    WHEN DATE_DIFF((SELECT d1 FROM bounds), first_seen, DAY) <= gap_days THEN 'new'\n    ELSE 'active'\n  END AS status\nFROM per_url\nORDER BY days_since_last_seen DESC, impressions_total DESC;",
    "notes": "- What it is for: the base report. It gives you one line per page with its whole life story in search.\n\n- DECLARE gap_days DEFAULT 28 : how many quiet days count as gone. Change this one number to make the report stricter or looser.\n- WHERE impressions > 0 : ignores rows where the page was not shown.\n- MIN(data_date) AS first_seen : the first day the page was ever shown.\n- MAX(data_date) AS last_seen : the last day the page was shown.\n- COUNT(DISTINCT data_date) AS active_days : on how many separate days the page was shown.\n- bounds : holds the last day in your data, used as today.\n- lifespan_days : how many days passed between the first and the last time it was shown.\n- days_since_last_seen : how long the page has been quiet.\n- CASE ... status : labels each page as dropped, new, or active.\n- ORDER BY : the longest quiet pages come first.\n\n- Note: run this one on its own, because DECLARE has to be the first line of the script.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q03",
    "title": "Newly served URLs",
    "category": "Lifecycle",
    "summary": "Find pages appearing in Search for the first time recently.",
    "sql": "-- 2. NEWLY SERVED URLS: pages shown in search for the first time recently\nSELECT\n  url,\n  MIN(data_date) AS first_impression_date,\n  COUNT(DISTINCT data_date) AS active_days,\n  SUM(impressions) AS impressions_total,\n  SUM(clicks) AS clicks_total\nFROM `{{TABLE}}`\nWHERE impressions > 0\nGROUP BY url\nHAVING first_impression_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 28 DAY)\nORDER BY impressions_total DESC;",
    "notes": "- What it is for: finding pages that just started being shown. This is the closest thing to a newly indexed list.\n\n- MIN(data_date) AS first_impression_date : the very first day the page appeared.\n- HAVING first_impression_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 28 DAY) : keeps only pages whose first day was in the last 28 days.\n- ORDER BY impressions_total DESC : the strongest new pages come first.\n\n- Tip: if you add your own publish dates next to this, you get time to first appearance, which is a much better indexing measure than anything in the Search Console screen.\n- Change 28 to 7 for a weekly check, or 90 for a quarterly one.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q04",
    "title": "Dropped URLs that mattered",
    "category": "Lifecycle",
    "summary": "Prioritize quiet pages that previously earned meaningful clicks.",
    "sql": "-- 3. DROPPED URLS THAT MATTERED: quiet now, but earned real clicks before\nWITH bounds AS (\n  SELECT MAX(data_date) AS d1 FROM `{{TABLE}}`\n),\nper_url AS (\n  SELECT\n    url,\n    MAX(data_date) AS last_seen,\n    SUM(impressions) AS impressions_total,\n    SUM(clicks) AS clicks_total,\n    SUM(IF(data_date >= DATE_SUB((SELECT d1 FROM bounds), INTERVAL 28 DAY),\n           clicks, 0)) AS clicks_last_28\n  FROM `{{TABLE}}`\n  WHERE impressions > 0\n  GROUP BY url\n)\nSELECT\n  url,\n  last_seen,\n  DATE_DIFF((SELECT d1 FROM bounds), last_seen, DAY) AS days_silent,\n  impressions_total,\n  clicks_total\nFROM per_url\nWHERE clicks_last_28 = 0\n  AND clicks_total >= 10\n  AND DATE_DIFF((SELECT d1 FROM bounds), last_seen, DAY) >= 28\nORDER BY clicks_total DESC;",
    "notes": "- What it is for: your fix-first list. It ignores pages that never mattered and shows only the ones that used to bring real traffic.\n\n- clicks_last_28 : clicks in the last 28 days of the data.\n- WHERE clicks_last_28 = 0 : the page brings no traffic now.\n- AND clicks_total >= 10 : but it brought at least 10 clicks in the past, so it is worth saving.\n- AND days_silent >= 28 : and it has been quiet for at least 4 weeks, so this is not a one week dip.\n- ORDER BY clicks_total DESC : the biggest traffic losses come first.\n\n- Change 10 to a higher number on big sites so the list stays short enough to act on.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q05",
    "title": "Resurrected URLs",
    "category": "Lifecycle",
    "summary": "Detect URLs that disappeared for a sustained period and later returned.",
    "sql": "-- 4. RESURRECTED URLS: pages that disappeared and later came back\nWITH active_days AS (\n  SELECT url, data_date\n  FROM `{{TABLE}}`\n  GROUP BY url, data_date\n  HAVING SUM(impressions) > 0\n),\nwith_prev AS (\n  SELECT\n    url,\n    data_date,\n    LAG(data_date) OVER (PARTITION BY url ORDER BY data_date) AS prev_date\n  FROM active_days\n)\nSELECT\n  url,\n  prev_date AS disappeared_after,\n  data_date AS returned_on,\n  DATE_DIFF(data_date, prev_date, DAY) - 1 AS days_missing\nFROM with_prev\nWHERE prev_date IS NOT NULL\n  AND DATE_DIFF(data_date, prev_date, DAY) > 28\nORDER BY days_missing DESC;",
    "notes": "- What it is for: pages that vanished and then returned. One line per disappearance, so a page can appear more than once.\n\n- active_days : the list of days each page was actually shown.\n- LAG(data_date) OVER (PARTITION BY url ORDER BY data_date) : looks at the previous day this same page was shown.\n- DATE_DIFF(...) > 28 : only counts it as a disappearance if more than 28 days passed between the two showings.\n- days_missing : how long the page was gone.\n\n- How to read it: a page that keeps disappearing and returning usually has a duplicate or canonical problem, not a ranking problem.\n- It also shows you whether a content refresh actually brought a page back, and how long that took.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q06",
    "title": "Monthly search footprint",
    "category": "Lifecycle",
    "summary": "Track URLs served, gained, and lost by month.",
    "sql": "-- 5. MONTHLY FOOTPRINT: how many URLs are served, gained, and lost each month\nWITH monthly AS (\n  SELECT\n    DATE_TRUNC(data_date, MONTH) AS month,\n    url\n  FROM `{{TABLE}}`\n  WHERE impressions > 0\n  GROUP BY month, url\n),\nflags AS (\n  SELECT\n    month,\n    url,\n    LAG(month) OVER (PARTITION BY url ORDER BY month) AS prev_active_month,\n    LEAD(month) OVER (PARTITION BY url ORDER BY month) AS next_active_month\n  FROM monthly\n)\nSELECT\n  month,\n  COUNT(*) AS urls_served,\n  COUNTIF(prev_active_month IS NULL\n          OR prev_active_month < DATE_SUB(month, INTERVAL 1 MONTH)) AS urls_gained,\n  COUNTIF(next_active_month IS NULL\n          OR next_active_month > DATE_ADD(month, INTERVAL 1 MONTH)) AS urls_lost_after\nFROM flags\nGROUP BY month\nORDER BY month;",
    "notes": "- What it is for: the big picture. One line per month showing whether the site is growing or shrinking in search.\n\n- DATE_TRUNC(data_date, MONTH) : turns every day into its month, so June 3 and June 20 both become June.\n- monthly : the list of pages shown in each month.\n- LAG(month) : the previous month this page was shown.\n- LEAD(month) : the next month this page was shown.\n- urls_served : how many different pages were shown that month.\n- urls_gained : pages that were not shown in the month before.\n- urls_lost_after : pages that were not shown in the month after.\n\n- How to read it: if gained and lost stay close every month, the site is churning instead of growing.\n- This is a good first chart for a client report, and it is cheap to run.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q07",
    "title": "Flapping URLs",
    "category": "Quality",
    "summary": "Find pages served on only a small share of the days they existed.",
    "sql": "-- 6. FLAPPING URLS: shown on only a small share of the days they existed\nSELECT\n  url,\n  MIN(data_date) AS first_seen,\n  MAX(data_date) AS last_seen,\n  COUNT(DISTINCT data_date) AS active_days,\n  DATE_DIFF(MAX(data_date), MIN(data_date), DAY) + 1 AS span_days,\n  ROUND(COUNT(DISTINCT data_date)\n        / (DATE_DIFF(MAX(data_date), MIN(data_date), DAY) + 1), 3) AS coverage_ratio,\n  SUM(impressions) AS impressions_total\nFROM `{{TABLE}}`\nWHERE impressions > 0\nGROUP BY url\nHAVING span_days >= 90 AND coverage_ratio < 0.30\nORDER BY impressions_total DESC;",
    "notes": "- What it is for: pages that are shown on and off instead of every day. These sit on the edge of the index.\n\n- active_days : the number of days the page was shown.\n- span_days : the number of days between its first and last showing.\n- coverage_ratio : active_days divided by span_days. A value of 1 means shown every single day. A value of 0.10 means shown on only one day out of ten.\n- HAVING span_days >= 90 : only looks at pages that have been around for at least 3 months.\n- AND coverage_ratio < 0.30 : keeps pages shown on less than a third of their days.\n\n- How to read it: on and off serving is usually a quality or duplicate signal. Fix these before writing anything new on the same topic.\n- Raise 0.30 to 0.50 if the list is too short, or lower it to 0.15 to see only the worst cases.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q08",
    "title": "Index status join",
    "category": "Quality",
    "summary": "Join Search Console performance with a URL Inspection results table.",
    "sql": "-- 7. REAL INDEX STATUS: join the export to URL Inspection API results\nWITH serving AS (\n  SELECT\n    url,\n    MAX(IF(impressions > 0, data_date, NULL)) AS last_impression_date,\n    SUM(impressions) AS impressions_total,\n    SUM(clicks) AS clicks_total\n  FROM `{{TABLE}}`\n  GROUP BY url\n)\nSELECT\n  i.url,\n  i.verdict,\n  i.coverage_state,\n  i.last_crawl_time,\n  i.google_canonical,\n  i.user_canonical,\n  s.last_impression_date,\n  IFNULL(s.impressions_total, 0) AS impressions_total,\n  IFNULL(s.clicks_total, 0) AS clicks_total\nFROM `{{INSPECTION_TABLE}}` AS i\nLEFT JOIN serving AS s\n  ON s.url = i.url\nWHERE i.coverage_state != 'Submitted and indexed'\nORDER BY impressions_total DESC;",
    "notes": "- What it is for: this is the only query here that tells you the true index status. All the others only tell you what was shown in search.\n\n- Before you run it: the Search Console export does not contain index status. You have to pull it yourself with the URL Inspection API and load the results into a table called url_inspection, with columns url, verdict, coverage_state, last_crawl_time, google_canonical, user_canonical.\n\n- serving : the shown in search side, one line per page, taken from the export.\n- LEFT JOIN : keeps every inspected page, even ones that were never shown in search.\n- verdict : PASS, NEUTRAL, or FAIL.\n- coverage_state : the real reason, for example Crawled currently not indexed, or Duplicate without user selected canonical.\n- google_canonical vs user_canonical : if these two differ, Google picked a different page than you did.\n- WHERE coverage_state != 'Submitted and indexed' : shows only the problem pages.\n\n- Why it matters: without this join you cannot tell a de-indexed page apart from a page that is indexed but simply never shown.\n\n- Note: searchdata_url_impression is your real table and is filled in. The url_inspection table is not part of the export and does not exist yet. This query will fail with Not found until you create it from URL Inspection API results.",
    "requiresInspectionTable": true
  },
  {
    "id": "q09",
    "title": "Topical coverage decay",
    "category": "Content",
    "summary": "Find URLs losing query variety before traffic disappears.",
    "sql": "-- 8. TOPICAL COVERAGE DECAY: URLs losing query variety before losing traffic\nWITH monthly AS (\n  SELECT\n    url,\n    DATE_TRUNC(data_date, MONTH) AS month,\n    COUNT(DISTINCT query) AS distinct_queries,\n    SUM(impressions) AS impressions\n  FROM `{{TABLE}}`\n  WHERE is_anonymized_query = FALSE\n  GROUP BY url, month\n),\nranked AS (\n  SELECT\n    url,\n    FIRST_VALUE(distinct_queries) OVER w AS queries_first_month,\n    LAST_VALUE(distinct_queries) OVER w AS queries_last_month,\n    FIRST_VALUE(month) OVER w AS first_month,\n    LAST_VALUE(month) OVER w AS last_month,\n    COUNT(*) OVER w AS months_active\n  FROM monthly\n  WINDOW w AS (\n    PARTITION BY url ORDER BY month\n    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\n  )\n)\nSELECT DISTINCT\n  url,\n  first_month,\n  last_month,\n  months_active,\n  queries_first_month,\n  queries_last_month,\n  queries_last_month - queries_first_month AS query_delta\nFROM ranked\nWHERE months_active >= 4\n  AND queries_first_month >= 10\n  AND queries_last_month < queries_first_month * 0.5\nORDER BY query_delta ASC;",
    "notes": "- What it is for: catching decay early. A page loses the variety of queries it ranks for before it loses its impressions, so this warns you months ahead of the impression reports.\n\n- COUNT(DISTINCT query) AS distinct_queries : how many different searches brought up this page in that month.\n- WHERE is_anonymized_query = FALSE : skips the rows where Google hides the search term for privacy, because those cannot be counted as separate queries.\n- FIRST_VALUE ... OVER w : the query count in the page's first month.\n- LAST_VALUE ... OVER w : the query count in the page's most recent month.\n- months_active >= 4 : ignores pages too new to judge.\n- queries_first_month >= 10 : ignores pages that never covered much.\n- queries_last_month < queries_first_month * 0.5 : keeps pages that lost more than half of their query variety.\n- ORDER BY query_delta ASC : the biggest losses come first, because the delta is a negative number.\n\n- How to read it: a page here is still getting traffic but is covering less than it used to. That is a gap to close in the content, not a page to delete.\n\n- Optional: add AND LOWER(search_type) = 'web' to the WHERE clause if you want web results only. Without it, a page counts as shown in search when it appeared in Discover or News.",
    "requiresInspectionTable": false
  },
  {
    "id": "q10",
    "title": "High impressions, low clicks",
    "category": "CTR",
    "summary": "Build a starting list of visible pages with weak click-through rates.",
    "sql": "-- 9. HIGH IMPRESSIONS, LOW CLICKS: the starting list\nSELECT\n  url,\n  SUM(impressions) AS impressions_total,\n  SUM(clicks) AS clicks_total,\n  ROUND(SAFE_DIVIDE(SUM(clicks), SUM(impressions)) * 100, 2) AS ctr_pct,\n  ROUND(SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1, 1) AS avg_position\nFROM `{{TABLE}}`\nWHERE data_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)\n  AND LOWER(search_type) = 'web'\nGROUP BY url\nHAVING impressions_total >= 1000 AND ctr_pct < 1.0\nORDER BY impressions_total DESC;",
    "notes": "- What it is for: the plain list of pages Google shows a lot but nobody clicks.\n\n- SAFE_DIVIDE(clicks, impressions) : the click through rate. SAFE_DIVIDE is used instead of a slash so a page with zero impressions returns empty instead of an error.\n- SAFE_DIVIDE(sum_top_position, impressions) + 1 : the average position. The export stores position starting from zero, so 1 is added to make it read like the Search Console screen.\n- WHERE data_date >= ... 90 DAY : looks at the last 3 months only. This also lowers the cost, because the table is split by date.\n- HAVING impressions >= 1000 AND ctr_pct < 1.0 : keeps pages with plenty of visibility and almost no clicks.\n\n- Note: 1000 and 1.0 are starting numbers, not rules. On a small site lower them. On a large site raise them until the list is short enough to act on.\n- Careful: a low rate on its own does not mean the page is broken. A page sitting at position 30 is supposed to have a low rate. Query 11 fixes that problem properly.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: an output column was named impressions, the same as a real column in the table. In a HAVING clause BigQuery reads the table column first, so it failed with a message about a column that is neither grouped nor aggregated. The output is now called impressions_total.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.",
    "requiresInspectionTable": false
  },
  {
    "id": "q11",
    "title": "Striking-distance pages",
    "category": "CTR",
    "summary": "Find URLs ranking from positions 5–20 with meaningful demand.",
    "sql": "-- 10. STRIKING DISTANCE: positions 5 to 20 with real impression volume\nSELECT\n  url,\n  SUM(impressions) AS impressions_total,\n  SUM(clicks) AS clicks_total,\n  ROUND(SAFE_DIVIDE(SUM(clicks), SUM(impressions)) * 100, 2) AS ctr_pct,\n  ROUND(SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1, 1) AS avg_position,\n  CAST(ROUND(SUM(impressions) * 0.05 - SUM(clicks)) AS INT64) AS clicks_within_reach\nFROM `{{TABLE}}`\nWHERE data_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)\n  AND LOWER(search_type) = 'web'\nGROUP BY url\nHAVING impressions_total >= 500\n   AND avg_position BETWEEN 5 AND 20\nORDER BY clicks_within_reach DESC;",
    "notes": "- What it is for: the best internal link targets on the whole site. These pages already rank, just not high enough to be clicked.\n\n- avg_position BETWEEN 5 AND 20 : the range where extra internal links move the needle most. Above position 5 the page is already visible, and below position 20 the problem is usually the content itself, not the linking.\n- impressions >= 500 : makes sure there is enough demand to be worth the work.\n- clicks_within_reach : a rough estimate of the clicks you would gain if the page reached a 5 percent rate.\n- ORDER BY clicks_within_reach DESC : the biggest wins come first.\n\n- Note: 0.05 is a flat assumption used only for sorting. It is not a promise of results. Query 11 replaces it with your own site data.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: an output column was named impressions, the same as a real column in the table. In a HAVING clause BigQuery reads the table column first, so it failed with a message about a column that is neither grouped nor aggregated. The output is now called impressions_total.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.",
    "requiresInspectionTable": false
  },
  {
    "id": "q12",
    "title": "CTR gap vs. your own curve",
    "category": "CTR",
    "summary": "Benchmark every page against your site's observed CTR by position.",
    "sql": "-- 11. CTR GAP: measure every page against your own site's curve\nWITH base AS (\n  SELECT\n    url,\n    SUM(impressions) AS impressions,\n    SUM(clicks) AS clicks,\n    SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1 AS avg_position\n  FROM `{{TABLE}}`\n  WHERE data_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)\n  AND LOWER(search_type) = 'web'\n  GROUP BY url\n),\nbanded AS (\n  SELECT *, CAST(FLOOR(avg_position) AS INT64) AS position_band\n  FROM base\n  WHERE impressions >= 100\n),\ncurve AS (\n  SELECT position_band, SAFE_DIVIDE(SUM(clicks), SUM(impressions)) AS expected_ctr\n  FROM banded\n  GROUP BY position_band\n)\nSELECT\n  b.url,\n  b.impressions,\n  b.clicks,\n  ROUND(b.avg_position, 1) AS avg_position,\n  ROUND(SAFE_DIVIDE(b.clicks, b.impressions) * 100, 2) AS ctr_pct,\n  ROUND(c.expected_ctr * 100, 2) AS expected_ctr_pct,\n  CAST(ROUND(b.impressions * c.expected_ctr - b.clicks) AS INT64) AS clicks_missed\nFROM banded AS b\nJOIN curve AS c USING (position_band)\nWHERE b.impressions * c.expected_ctr - b.clicks > 0\nORDER BY clicks_missed DESC;",
    "notes": "- What it is for: the honest version of the low click report. Instead of one flat rule for the whole site, it asks whether each page performs worse than your other pages sitting at the same position.\n\n- base : one line per page with its clicks, impressions, and average position.\n- position_band : rounds the position down to a whole number, so 7.4 and 7.8 both land in band 7.\n- curve : the average rate your own site gets at each position. This is your real benchmark, built from your data, not from a published study.\n- JOIN curve USING (position_band) : matches each page to the benchmark for its own position.\n- expected_ctr_pct : the rate this page should get at that position.\n- clicks_missed : impressions multiplied by the expected rate, minus the clicks it actually got. This is the gap in real clicks.\n- WHERE ... > 0 : keeps only pages that fall short.\n\n- How to use it: this is the ranking to trust. A page missing 400 clicks at position 8 matters far more than a page with a 0.2 percent rate at position 40.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.",
    "requiresInspectionTable": false
  },
  {
    "id": "q13",
    "title": "Query-level click losses",
    "category": "Content",
    "summary": "Find exact searches where a visible page received no clicks.",
    "sql": "-- 12. QUERY LEVEL LOSSES: searches where a page is seen but never clicked\nWITH per_query AS (\n  SELECT\n    url,\n    query,\n    SUM(impressions) AS impressions,\n    SUM(clicks) AS clicks,\n    SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1 AS avg_position\n  FROM `{{TABLE}}`\n  WHERE is_anonymized_query = FALSE\n    AND data_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)\n    AND LOWER(search_type) = 'web'\n  GROUP BY url, query\n)\nSELECT\n  url,\n  query,\n  impressions,\n  clicks,\n  ROUND(SAFE_DIVIDE(clicks, impressions) * 100, 2) AS ctr_pct,\n  ROUND(avg_position, 1) AS avg_position\nFROM per_query\nWHERE impressions >= 200\n  AND clicks = 0\n  AND avg_position <= 20\nORDER BY impressions DESC;",
    "notes": "- What it is for: moving from the page level down to the search level. It tells you which exact searches a page is shown for and never clicked on.\n\n- GROUP BY url, query : one line per page and search pair instead of one line per page.\n- is_anonymized_query = FALSE : skips the rows where Google hides the search term.\n- impressions >= 200 AND clicks = 0 : shown often, clicked never.\n- avg_position <= 20 : the page was visible enough that a click was realistic.\n\n- How to use it for linking: the search terms in this list are the words you should be using as anchor text when you link to this page. You are pointing links at a page using the exact language it is already being shown for.\n- It also tells you what to fix in the title and description, because a zero here often means the page is being shown for the wrong meaning.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.",
    "requiresInspectionTable": false
  },
  {
    "id": "q14",
    "title": "Cannibalization",
    "category": "Content",
    "summary": "Reveal queries split across multiple URLs on your site.",
    "sql": "-- 13. CANNIBALIZATION: several pages splitting one search between them\nWITH per_query AS (\n  SELECT\n    query,\n    url,\n    SUM(impressions) AS impressions,\n    SUM(clicks) AS clicks,\n    SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1 AS avg_position\n  FROM `{{TABLE}}`\n  WHERE is_anonymized_query = FALSE\n    AND data_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)\n    AND LOWER(search_type) = 'web'\n  GROUP BY query, url\n),\nranked AS (\n  SELECT\n    *,\n    ROW_NUMBER() OVER (PARTITION BY query ORDER BY impressions DESC) AS url_rank,\n    COUNT(*) OVER (PARTITION BY query) AS urls_on_query,\n    SUM(impressions) OVER (PARTITION BY query) AS query_impressions\n  FROM per_query\n)\nSELECT\n  query,\n  query_impressions,\n  urls_on_query,\n  url_rank,\n  url,\n  impressions,\n  clicks,\n  ROUND(avg_position, 1) AS avg_position\nFROM ranked\nWHERE urls_on_query >= 2\n  AND query_impressions >= 500\n  AND url_rank <= 4\nORDER BY query_impressions DESC, url_rank;",
    "notes": "- What it is for: finding searches where two or more of your own pages compete, which splits the impressions and holds all of them down.\n\n- ROW_NUMBER() OVER (PARTITION BY query ORDER BY impressions DESC) : ranks your pages against each other for the same search. Rank 1 is the page Google prefers.\n- COUNT(*) OVER (PARTITION BY query) : how many of your pages show up for that search.\n- SUM(impressions) OVER (PARTITION BY query) : the total demand for that search across all your pages.\n- urls_on_query >= 2 : keeps only the searches where you compete with yourself.\n- url_rank <= 4 : shows the top 4 competing pages per search so the output stays readable.\n\n- How to use it for linking: send your internal links for that search to the rank 1 page and remove or repoint the links feeding the others. Splitting links across competing pages is usually what created the problem.\n- Careful: two pages on one search is not always wrong. Check whether the search has two real meanings before merging anything.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.",
    "requiresInspectionTable": false
  },
  {
    "id": "q15",
    "title": "Pages that lost ground",
    "category": "Content",
    "summary": "Compare current ranking position with each URL's best month.",
    "sql": "-- 14. LOST GROUND: pages ranking far below their own best position\nWITH monthly AS (\n  SELECT\n    url,\n    DATE_TRUNC(data_date, MONTH) AS month,\n    SUM(impressions) AS impressions_total,\n    SUM(clicks) AS clicks_total,\n    SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1 AS avg_position\n  FROM `{{TABLE}}`\n  WHERE LOWER(search_type) = 'web'\n  GROUP BY url, month\n  HAVING impressions_total >= 50\n),\nagg AS (\n  SELECT\n    url,\n    MIN(avg_position) AS best_position,\n    ARRAY_AGG(avg_position      IGNORE NULLS ORDER BY month DESC LIMIT 1)[OFFSET(0)] AS current_position,\n    ARRAY_AGG(impressions_total IGNORE NULLS ORDER BY month DESC LIMIT 1)[OFFSET(0)] AS current_impressions,\n    ARRAY_AGG(clicks_total      IGNORE NULLS ORDER BY month DESC LIMIT 1)[OFFSET(0)] AS current_clicks\n  FROM monthly\n  GROUP BY url\n)\nSELECT\n  url,\n  ROUND(best_position, 1) AS best_position,\n  ROUND(current_position, 1) AS current_position,\n  ROUND(current_position - best_position, 1) AS positions_lost,\n  current_impressions,\n  current_clicks\nFROM agg\nWHERE current_position - best_position >= 3\n  AND current_impressions >= 200\nORDER BY current_impressions DESC;",
    "notes": "- What it is for: pages that used to rank well and slipped. They still collect impressions but have stopped collecting clicks.\n\n- monthly : one line per page per month, ignoring months with fewer than 50 impressions so a single quiet week does not distort the result.\n- MIN(avg_position) AS best_position : the best month this page ever had.\n- ARRAY_AGG(... ORDER BY month DESC LIMIT 1)[OFFSET(0)] : takes the value from the most recent month. It sorts the months newest first, keeps one, and reads it.\n- positions_lost : how far the page has fallen from its own best.\n- >= 3 : only pages that lost at least 3 positions.\n\n- How to use it for linking: these are proven pages, so they respond to link support faster than anything new. A page that held position 4 and now sits at position 9 is the easiest win on this whole list.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: an output column was named impressions, the same as a real column in the table. In a HAVING clause BigQuery reads the table column first, so it failed with a message about a column that is neither grouped nor aggregated. The output is now called impressions_total.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.\n- Hardened: added IGNORE NULLS inside ARRAY_AGG, because ARRAY_AGG raises an error if a null reaches it.",
    "requiresInspectionTable": false
  },
  {
    "id": "q16",
    "title": "Anchor-text candidates",
    "category": "Internal links",
    "summary": "Assign up to three strong, non-competing query phrases to each URL.",
    "sql": "-- 15. ANCHOR TEXT CANDIDATES: one search term owned by one page only\nWITH per_query AS (\n  SELECT\n    url,\n    query,\n    SUM(impressions) AS impressions,\n    SUM(clicks) AS clicks,\n    SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1 AS avg_position\n  FROM `{{TABLE}}`\n  WHERE is_anonymized_query = FALSE\n    AND data_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)\n    AND LOWER(search_type) = 'web'\n  GROUP BY url, query\n),\nowner AS (\n  SELECT\n    *,\n    ROW_NUMBER() OVER (PARTITION BY query ORDER BY impressions DESC) AS owner_rank\n  FROM per_query\n),\nbest AS (\n  SELECT\n    *,\n    ROW_NUMBER() OVER (PARTITION BY url ORDER BY impressions DESC) AS anchor_rank\n  FROM owner\n  WHERE owner_rank = 1\n    AND impressions >= 100\n    AND avg_position BETWEEN 4 AND 20\n)\nSELECT\n  url,\n  anchor_rank,\n  query AS anchor_text_candidate,\n  impressions,\n  clicks,\n  ROUND(avg_position, 1) AS avg_position\nFROM best\nWHERE anchor_rank <= 3\nORDER BY url, anchor_rank;",
    "notes": "- What it is for: building the actual anchor text list before you place a single link.\n\n- owner_rank = 1 : for each search term, keeps only the page that gets the most impressions for it. This makes sure no two pages are ever given the same anchor text, which is what causes pages to compete with each other.\n- anchor_rank : ranks the search terms inside each page, best first.\n- anchor_rank <= 3 : gives you up to 3 anchor text options per page.\n- avg_position BETWEEN 4 AND 20 : only terms where the page is close enough for links to help.\n\n- How to use it: for every page in your priority list, take its 3 candidates and use them as the anchor text on the new internal links. Vary between the 3 rather than repeating one word.\n- Because each term belongs to exactly one page, following this list makes cannibalization less likely instead of more likely.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.",
    "requiresInspectionTable": false
  },
  {
    "id": "q17",
    "title": "Internal-link priority",
    "category": "Internal links",
    "summary": "Rank URLs by missed clicks and likely responsiveness to link support.",
    "sql": "-- 16. INTERNAL LINK PRIORITY: one ranked list with suggested link counts\nWITH base AS (\n  SELECT\n    url,\n    SUM(impressions) AS impressions_total,\n    SUM(clicks) AS clicks_total,\n    SAFE_DIVIDE(SUM(sum_position), SUM(impressions)) + 1 AS avg_position\n  FROM `{{TABLE}}`\n  WHERE data_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)\n    AND LOWER(search_type) = 'web'\n  GROUP BY url\n  HAVING impressions_total >= 200\n),\nbanded AS (\n  SELECT *, CAST(FLOOR(avg_position) AS INT64) AS position_band FROM base\n),\ncurve AS (\n  SELECT position_band,\n         SAFE_DIVIDE(SUM(clicks_total), SUM(impressions_total)) AS expected_ctr\n  FROM banded GROUP BY position_band\n),\nscored AS (\n  SELECT\n    b.url,\n    b.impressions_total,\n    b.clicks_total,\n    b.avg_position,\n    b.impressions_total * c.expected_ctr - b.clicks_total AS clicks_missed,\n    CASE\n      WHEN b.avg_position BETWEEN 4 AND 10 THEN 1.0\n      WHEN b.avg_position > 10 AND b.avg_position <= 20 THEN 0.7\n      WHEN b.avg_position < 4 THEN 0.3\n      ELSE 0.2\n    END AS position_weight\n  FROM banded AS b\n  JOIN curve AS c USING (position_band)\n)\nSELECT\n  url,\n  ROUND(avg_position, 1) AS avg_position,\n  impressions_total,\n  clicks_total,\n  CAST(ROUND(clicks_missed) AS INT64) AS clicks_missed,\n  ROUND(clicks_missed * position_weight, 1) AS link_priority_score,\n  CASE\n    WHEN clicks_missed * position_weight >= 500 THEN 'add 8 to 12 internal links'\n    WHEN clicks_missed * position_weight >= 200 THEN 'add 5 to 8 internal links'\n    WHEN clicks_missed * position_weight >= 50  THEN 'add 3 to 5 internal links'\n    ELSE 'add 1 to 2 internal links'\n  END AS suggested_action\nFROM scored\nWHERE clicks_missed > 0\nORDER BY link_priority_score DESC\nLIMIT 200;",
    "notes": "- What it is for: the one list you hand to the team. It combines the missed clicks from query 11 with how much links can realistically help at that position, then turns the result into a number of links per page.\n\n- clicks_missed : the same gap calculation as query 11, measured against your own site curve.\n- position_weight : how responsive the page is to link support. Positions 4 to 10 get the full weight because that is where extra links move pages fastest. Positions 11 to 20 get 0.7. Pages already in the top 3 get 0.3, since there is little room left. Everything past 20 gets 0.2, because links alone will not fix a page that far back.\n- link_priority_score : missed clicks multiplied by that weight. It ranks by opportunity and by how likely linking is to work.\n- suggested_action : turns the score into a link count so the work can be handed over without further analysis.\n- LIMIT 200 : keeps the output to a workload a team can actually finish.\n\n- Important: the weights of 1.0, 0.7, 0.3, 0.2 and the link counts of 8 to 12, 5 to 8, 3 to 5, 1 to 2 are judgement calls set by hand, not values calculated from your data. Adjust them to match how your site has responded to linking in the past, and keep them the same across runs so the scores stay comparable month to month.\n- Run query 15 next to get the anchor text for each page on this list.\n\n- Corrected: this query first used sum_top_position, which is a column of the site table, not the URL table. The URL table calls it sum_position. It has been changed, otherwise BigQuery returns Unrecognized name.\n- Corrected: an output column was named impressions, the same as a real column in the table. In a HAVING clause BigQuery reads the table column first, so it failed with a message about a column that is neither grouped nor aggregated. The output is now called impressions_total.\n- Corrected: added LOWER(search_type) = 'web'. Without it the numbers mix web results with Discover, News, Image, and Video, and Discover rows have no meaningful position, so the average position and the rate were both distorted.",
    "requiresInspectionTable": false
  }
];
